name: Docker Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t firstrepo-docker-image .
        
      - name: Login to Docker Hub
        run: docker login -u yipingzhou -p QWEszxc1ping
        
      - name: Push Docker image to Docker Hub
        run: docker push firstrepo-docker-image:latest
